gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'git.shouba.cn'
  container_name: gitlab
  # privileged: true
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # GitLab URL
      external_url 'https://git.shouba.cn'

      # Time zone
      gitlab_rails['time_zone'] = 'Asia/Shanghai'

      # GitLab email server settings
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.qiye.aliyun.com"
      gitlab_rails['smtp_port'] = 465
      gitlab_rails['smtp_user_name'] = "shoubaguanfang@shoubakeji.com"
      gitlab_rails['smtp_password'] = ""
      gitlab_rails['smtp_domain'] = "shoubakeji.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = false
      gitlab_rails['smtp_tls'] = true

      # Email Settings
      gitlab_rails['gitlab_email_from'] = 'shoubaguanfang@shoubakeji.com'
      gitlab_rails['gitlab_email_display_name'] = 'gitlab'
      gitlab_rails['gitlab_email_reply_to'] = 'shoubaguanfang@shoubakeji.com'

      # Prometheus Alertmanager
      alertmanager['admin_email'] = 'weileiming@shoubakeji.com'

      # SSH
      gitlab_rails['gitlab_shell_ssh_port'] = 22
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/Users/leiming/Documents/docker/gitlab/config:/etc/gitlab'
    - '/Users/leiming/Documents/docker/gitlab/logs:/var/log/gitlab'
    - '/Users/leiming/Documents/docker/gitlab/data:/var/opt/gitlab'
