gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  container_name: gitlab
  environment:
    TZ: 'Asia/Shanghai'
    GITLAB_OMNIBUS_CONFIG: |
      # GitLab URL
      # external_url 'https://gitlab.example.com'
      external_url 'http://localhost:9090'

      # Time zone
      gitlab_rails['time_zone'] = 'Asia/Shanghai'

      # GitLab email server settings
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.263.net"
      gitlab_rails['smtp_port'] = 465
      gitlab_rails['smtp_user_name'] = "weilm@haiyungroup.com"
      gitlab_rails['smtp_password'] = ""
      gitlab_rails['smtp_domain'] = "haiyungroup.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = true

      # Email Settings
      gitlab_rails['gitlab_email_from'] = 'weilm@haiyungroup.com'
      gitlab_rails['gitlab_email_display_name'] = 'gitlab'
      gitlab_rails['gitlab_email_reply_to'] = 'weilm@haiyungroup.com'

      # Prometheus Alertmanager
      alertmanager['admin_email'] = 'weilm@haiyungroup.com'

      # SSH
      gitlab_rails['gitlab_shell_ssh_port'] = 9022
  ports:
    - '9090:9090'
    - '9022:22'
  volumes:
    # - '/srv/gitlab/config:/etc/gitlab'
    # - '/srv/gitlab/logs:/var/log/gitlab'
    # - '/srv/gitlab/data:/var/opt/gitlab'

    - '/Users/leiming/Documents/docker/gitlab/config:/etc/gitlab'
    - '/Users/leiming/Documents/docker/gitlab/logs:/var/log/gitlab'
    - '/Users/leiming/Documents/docker/gitlab/data:/var/opt/gitlab'
